version: '3.8'

services:

  db:
    container_name: md_db
    image: postgres:13.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=movie_db
      - POSTGRES_PASSWORD=movie_db_password
      - POSTGRES_DB=movie_db

  backend:
    container_name: md_backend
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    ports:
      - "8000:8000"

  frontend:
    container_name: md_frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file:
      - frontend/.env
    ports:
      - "8080:8080"

volumes:
  db_data: